# Generated by Django 2.0.5 on 2018-11-03 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=200)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('wid', models.IntegerField(default=0, unique=True)),
                ('stravaId', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('strDist', models.CharField(default='', max_length=10)),
                ('strTime', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GpsCoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_index', models.IntegerField(default=0)),
                ('gps_lat', models.FloatField(default=0)),
                ('gps_long', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_index', models.IntegerField(default=0)),
                ('lap_start_index', models.IntegerField(default=0)),
                ('lap_end_index', models.IntegerField(default=0)),
                ('lap_distance', models.IntegerField(default=0)),
                ('lap_time', models.DurationField(default=0)),
                ('lap_average_speed', models.FloatField(default=0)),
                ('lap_average_cadence', models.FloatField(default=0)),
                ('lap_pace_zone', models.IntegerField(default=0)),
                ('lap_total_elevation_gain', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('url', models.CharField(default='', max_length=200)),
                ('clientID', models.CharField(default='', max_length=200)),
                ('clientSecret', models.CharField(default='', max_length=200)),
                ('callbackURL', models.CharField(default='', max_length=200)),
                ('dateLogin', models.DateField(verbose_name=datetime.datetime(2018, 11, 3, 14, 12, 32, 952917, tzinfo=utc))),
                ('userName', models.CharField(default='', max_length=20)),
                ('lastUpdate', models.DateTimeField(default=datetime.date(2000, 1, 1))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('actId', models.IntegerField(default=0)),
                ('resolution', models.IntegerField(default=1000)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strava2.Workout'),
        ),
        migrations.AddField(
            model_name='lap',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laps', to='strava2.Workout'),
        ),
        migrations.AddField(
            model_name='gpscoord',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gps', to='strava2.Workout'),
        ),
        migrations.AddField(
            model_name='activity',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='strava2.Workout'),
        ),
    ]
