# Generated by Django 2.0.5 on 2018-11-03 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('strava2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='lap_average_cadence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='login',
            name='dateLogin',
            field=models.DateField(verbose_name=datetime.datetime(2018, 11, 3, 16, 47, 26, 349387, tzinfo=utc)),
        ),
    ]
