# Generated by Django 2.0.5 on 2018-11-03 17:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('strava2', '0002_auto_20181103_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='act', to='strava2.Workout'),
        ),
        migrations.AlterField(
            model_name='login',
            name='dateLogin',
            field=models.DateField(verbose_name=datetime.datetime(2018, 11, 3, 17, 20, 28, 794504, tzinfo=utc)),
        ),
    ]
