# Generated by Django 2.0.5 on 2018-11-03 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('strava2', '0003_auto_20181103_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='resolution',
        ),
        migrations.AddField(
            model_name='activity',
            name='resolution',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='login',
            name='dateLogin',
            field=models.DateField(verbose_name=datetime.datetime(2018, 11, 3, 17, 22, 52, 997482, tzinfo=utc)),
        ),
    ]
