# Generated by Django 2.0.5 on 2018-11-03 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('strava2', '0004_auto_20181103_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='dateLogin',
            field=models.DateField(verbose_name=datetime.datetime(2018, 11, 3, 18, 15, 41, 964638, tzinfo=utc)),
        ),
    ]
