# Generated by Django 2.0.5 on 2018-11-10 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('strava2', '0005_auto_20181103_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='lap_start_time',
            field=models.DateField(default=datetime.datetime(2018, 11, 10, 18, 41, 33, 574233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='login',
            name='dateLogin',
            field=models.DateField(verbose_name=datetime.datetime(2018, 11, 10, 18, 41, 33, 63674, tzinfo=utc)),
        ),
    ]
